spring:
  application:
    name: 'comanda-digital'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost:3308/comanda_digital'
    username: 'docker'
    password: 'admin123'
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

server:
  port: 8081

